In [22]:
def make_islands(n, low=10, high=101):
    islands = np.random.randint(low, high, n+2)
    islands[0] = 0
    islands[-1] = 0
    return islands
islands=make_islands(10)
islands

array([ 0, 48, 11, 96, 68, 98, 87, 47, 30, 24, 87,  0])

In [17]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from functools import partial

In [6]:
make_islands(10)

array([ 0, 10, 52, 52, 33, 43, 92, 50, 54, 74, 68,  0])

In [18]:
def hop(islands, start=1, niter=1000):
    pos = start
    pop = islands[pos]
    thetas = np.zeros(niter+1, dtype='int')
    thetas[0] = pos
    for i in range(niter):
        # generate sample from proposal distribution
        k = np.random.choice([-1, 1], 1)
        next_pos = pos + k
        # evaluate unnormalized target distribution at proposed position
        next_pop = islands[next_pos]
        # calculate acceptance probability
        p = min(1, next_pop/pop)
        # use uniform random to decide accept/reject proposal
        if np.random.random() < p:
            pos = next_pos
            pop = next_pop
        thetas[i+1] = pos
    return thetas

In [8]:
islands = make_islands(10)
thetas = hop(islands, start=1, niter=10000)

In [12]:
thetas = np.zeros(8, dtype='int')
thetas

array([0, 0, 0, 0, 0, 0, 0, 0])